config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  resources :blogs do
    collection do
      post :confirm
    end
  end

  resources :users, only: [:new, :create ]
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  
  mount_uploader :image, ImageUploader
  validates :content,
    length: {in: 0..63206}  
  validates :content, presence: true, if: :image?
  validates :image, presence: true, if: :content?
  
  private
  def image?
    self.image == ""
  end
  def content?
    self.content == ""
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :blogs
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  def authenticate_user
    if @current_user == nil
      flash[:notice] = t('notice.login_needed')
      redirect_to new_session_path
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
    
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    unless current_user
      redirect_to blogs_path, notice: "ログインしてください"
    else
      @blog = Blog.new
    end
  end

  def confirm
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    render :new if @blog.invalid?
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    if params[:back]
      render :new
    else
      if @blog.save
        redirect_to blogs_path, notice: "投稿しました"
      else
        render :new
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'ブログを編集しました' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'ブログを削除しました' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_blog
    @blog = Blog.find(params[:id])
  end

  def user_select
    if  current_user == current_user_blog.user_id
      redirect_to blogs_path, notice: "この操作はできません"
    end
  end

  # Only allow a list of trusted parameters through.
  def blog_params
    params.require(:blog).permit(:content, :image, :image_cache)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to blogs_path, notice: "ログインしました"
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save 
      redirect_to blogs_path, notice: "アカウントを作成しました!ようこそFacebookへ"
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def new_or_edit
    if action_name == 'new' || action_name == 'create' || action_name == 'confirm' 
      confirm_blogs_path
    else action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local:true ,url:new_or_edit) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :投稿を作成 %>
    <p class="text-area"><%= form.text_area :content %>
  </div>

  <div class="field select_image">
    <%= form.label :写真 %>
    <p class = "select_image"><%= form.file_field :image %></P>
    <P><%= form.hidden_field :image_cache %></P>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/confirm.html.erb

<h3 class="confirm_title">以下の内容で、投稿する。</h3>
<%= form_with(model: @blog , url: blogs_path, local:true )do |form| %>
<%= form.hidden_field :content %>
<%= form.hidden_field :image_cache %>
<p class="confirm_content">投稿内容:<%= @blog.content %></p>
<p class="confirm_content"><%= image_tag @blog.image.url if @blog.image.url %></p>
<%= form.submit "投稿する" %>
<%= form.submit "戻る",name: 'back' %>
<% end %>

app/views/blogs/edit.html.erb
<h1>投稿を編集</h1>
<p>
  <%= image_tag @blog.image.url if @blog.image.url %>
</p>
<%= render 'form', blog: @blog %>

<%= link_to '投稿を確認', @blog %> |
<%= link_to '戻る', blogs_path %>

app/views/blogs/index.html.erb
<div class="container">
  <ul class="row"><h1>Facebook</h1></ul>
  <br>
  <br>
  <div class="row">
    <button type="button" class="btn btn-primary btn-lg " aria-label="Left Align">
      <%= link_to '今の気持ちをシェアしよう', new_blog_path %>
    </button>
  </div>
  <br>
  <br>
  <br>
  <div class="row"><h3>みんなの投稿</h3></div>
  <div class="row">
    <% @blogs.each do |blog| %>
      <p class = "index_content"><%= blog.user.name %></p>
      <p class = "index_content"><%= blog.content %></p>
      <p class = "index_image"><%= image_tag blog.image.url if blog.image.url %></p>
      <div class="edits">
        <p class="col-sm-6 col-md-3"><%= link_to '投稿を確認', blog %></p>
        <p class="col-sm-6 col-md-3"><%= link_to '投稿を編集', edit_blog_path(blog) %></p>
        <p class="col-sm-6 col-md-3"><%= link_to '投稿を削除', blog, method: :delete, data: { confirm: 'この投稿を削除してよろしいですか？' } %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/blogs/new.html.erb
<h1>Facebook</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>投稿内容</strong>
  <%= @blog.content %>
</p>
<p>
  <%= image_tag @blog.image.url if @blog.image.url %>
</p>

<%= link_to '編集へ', edit_blog_path(@blog) %> |
<%= link_to '戻る', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleF</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <p><a href="#">ページのトップへ</a></p>
    </header>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <% if logged_in? %>
      <%= link_to "ログアウト", session_path(current_user.id), method: :delete %>
    <% else %>
    　<%= link_to "新規登録", new_user_path %>
      <%= link_to "ログイン", new_session_path %>
    <% end %>
    <div class="new_conteiner">
    <%= yield %>
    </div>
    <footer>
      <p> Facebook株式会社</p>
      <p>© 2009-2020 Facebook Corp.</p>
    </footer>
  </body>
</html>

app/views/users/new.html.erb

<h1>アカウント登録</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>  
  <div class="user_new">
    <%= f.label :名前 %>
    <%= f.text_field :name %>
    </div>
    <div class="user_new">
    <%= f.label :メール %>
    <%= f.email_field :email %>
  </div>
  <div class="user_new">
    <%= f.label :パスワード %>
    <%= f.password_field :password %>
  </div>
  <div class="user_new">
    <%= f.label :パスワード確認 %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="user_new">
    <%= f.submit "アカウントを作成" %>
<% end %>
<%= link_to 'みんなの投稿を見る', blogs_path %>